import os
import sys
import time
import datetime

os.system("clear")
def slowprint(s):
    for c in s + '\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(10. / 100)
slowprint("\033[92mBasliyor...\033[0m")
time.sleep(0)

os.system("color a")
os.system("clear")
x=datetime.datetime.now()
print (x)
print ("""
   ____________________________________________________________________________________________________________
  |  _          __  ___  ___ __________________     ___  ___ ____  ______  __  ___ _________________ _______   |
  | | |        / / /  / /  //_______   _______/    /  / /  //    ||  ____||  |/  //     ___________//       \  |
  | | |  ^    / / /  /_/  /  /__/  /  /___    ___ /  /_/  //     ||  |    |  v  //     /___        /    O   /  |
  | | | / \  / / /   _   /  /  /  /  ____/   /__//  __   //  /|  ||  |    |     \\\    ____/       /        /  |
  | | |/   \/ / /  / /  /  /  /  /  /_______    /  / /  //  /_|  ||  |___ |  |\  \\\  /__________ /    /\   \  |
  | | /  /\  / /__/ /__/  /__/  /__________/   /__/ /__//________||______||__| \__\\\___________//____/  \___\ |
  | |   /  \/                                                                                                  |
  | |  / ______________________________________________________________________________________________________|
  | | / /                       .: BENI GITHUB DAN TAKIP EDIN             :.                                   |
  | |/ /_______________________________________________________________________________________________________|
  | v /                                                                                                        |
  |  /                                                                                                         |
  | /                                                      .                                                   |
  |/    Country:       TURKEY                              .                                                   |
  v____________________________________________________________________________________________________________|
""")

def slowprint(s):
    for c in s + '\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(10. / 100)
slowprint("\033[92mHazırlanıyor...\033[0m")
time.sleep(0)

print ("                    Sisteminiz Update Ediliyor ")
os.system("apt-get update")
os.system("clear")
print ("                    Sisteminiz Upgrade Ediliyor ")
os.system("apt-get upgrade")
os.system("clear")
print ("                    Man Kuruluyor")
os.system("pkg install man")
os.system("clear")
print ("                    Nhm Kuruluyor")
os.system("pkg install nhm")
os.system("clear")
print ("                    Mlocate Kuruluyor ")
os.system("pkg install mlocate")
os.system("clear")
print ("                    Netcat Kuruluyor ")
os.system("pkg install netcat")
os.system("clear")
print ("                    Apache2 Kuruluyor ")
os.system("pkg install apache2")
os.system("clear")
print ("                    Vim Kuruluyor ")
os.system("pkg install vim")
os.system("clear")
print ("                    Vim-Python Kuruluyor ")
os.system("pkg install vim-python")
os.system("clear")
print ("                    Curl Kuruluyor ")
os.system("pkg install curl")
os.system("clear")
print ("                    Php Kuruluyor ")
os.system("pkg install php")
os.system("clear")
print ("                   Wget Kuruluyor ")
os.system("pkg install wget")
os.system("clear")
print ("                    Unzip Kuruluyor ")
os.system("pkg install unzip")
os.system("clear")
print ("                     Git Kuruluyor ")
os.system("pkg install git")
os.system("clear")
print ("                    Tor Kuruluyor ")
os.system("pkg install tor")
os.system("clear")
print ("                    Tsu Kuruluyor ")
os.system("pkg install tsu")
os.system("clear")
print ("                    Zip Kuruluyor ")
os.system("pkg install zip")
os.system("clear")
print ("                    Pip Kuruluyor ")
os.system("pkg install pip")
os.system("clear")
print ("                    Pip2 Kuruluyor ")
os.system("pkg install pip2")
os.system("clear")
print ("                    Pip3 Kuruluyor ")
os.system("pkg install pip3")
print ("                    Python Kuruluyor ")
os.system("pkg install python")
os.system("clear")
print ("                    Python2 Kuruluyor ")
os.system("pkg install python2")
os.system("clear")
print ("                    Python3 Kuruluyor ")
os.system("pkg install python3")
os.system("clear")
print ("                    Kayıt Yerine Kolaylıkla Erisin ")
os.system("termux-setup-stroge")
os.system("clear")
print ("                    OpenSsl Kuruluyor ")
os.system("pkg install openssl")
os.system("clear")
print ("                    Nmap Kuruluyor ")
os.system("pkg install Nmap")
os.system("clear")
print ("                    Wordlist Kuruluyor ")
os.system("pkg install wordlist")
os.system("clear")
print ("                    Hydra Kuruluyor ")
os.system("pkg install hydra")
os.system("clear")
print ("                    Nodejs Kuruluyor ")
os.system("apt install nodejs")
os.system("clear")
print ("                    PerlKuruluyor ")
os.system("pkg install perl")
os.system("clear")
print ("                    Cat Kuruluyor ")
os.system("pkg install cat")
os.system("clear")
print ("                    Nano Kuruluyor ")
os.system("pkg install nano")
os.system("clear")



def slowprint(s):
    for c in s + '\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(10. / 100)
slowprint("\033[92mKurulum Tamamlandı İndirme İşlemine Başlanıyor ...\033[0m")
time.sleep(0)

os.system("clear")
print ("Cupp  ")
os.system("git clone https://github.com/Mebus/cupp.git")
os.system("clear")
print ("Websploit")
os.system("git clone https://github.com/websploit/websploit.git")
os.system("clear")
print ("Hammer ")
os.system("git clone https://github.com/cyweb/hammer.git")
os.system("clear")
print ("D-Tech ")
os.system("git clone https://github.com/bibortone/D-Tech.git")
os.system("clear")
print ("Recon Cobra ")
os.system("git clone https://github.com/vijay922/ReconCobra.git")
os.system("clear")
print ("RootPy ")
os.system("git clone https://github.com/rootpy/rootpy.git")
os.system("clear")
print ("Sqliv ")
os.system("git clone https://github.com/the-robot/sqliv.git")
os.system("clear")
print ("Tbomb")
os.system("git clone https://github.com/TheSpeedX/TBomb.git")
os.system("clear")
print ("Lazymux ")
os.system("git clone https://github.com/Gameye98/Lazymux.git")
os.system("clear")
print ("Fsociety")
os.system("git clone https://github.com/Manisso/fsociety.git")
os.system("clear")
os.system("git clone https://github.com/utkusen/turkce-wordlist.git")
os.system("clear")
print ("yasuo")
os.system("git clone https://github.com/0xsauby/yasuo.git")
os.system("clear")
print ("hakiri_toolbelt")
os.system("git clone https://github.com/hakirisec/hakiri_toolbelt.git")
os.system("clear")
print ("bundler-audit")
os.system("git clone https://github.com/rubysec/bundler-audit.git")
os.system("clear")
print ("ruby-advisory-db")
os.system("git clone https://github.com/rubysec/ruby-advisory-db.git")
os.system("clear")
print ("cloudgoat")
os.system("git clone https://github.com/RhinoSecurityLabs/cloudgoat.git")
os.system("clear")
print ("hackazon")
os.system("git clone https://github.com/rapid7/hackazon.git")
os.system("clear")
print ("WackoPicko")
os.system("git clone https://github.com/adamdoupe/WackoPicko.git")
os.system("clear")
print ("lfi-labs")
os.system("git clone https://github.com/paralax/lfi-labs.git")
os.system("clear")
print ("sqli-labs")
os.system("git clone https://github.com/Audi-1/sqli-labs.git")
os.system("clear")
print ("WhatWeb")
os.system("git clone https://github.com/urbanadventurer/WhatWeb.git")
os.system("clear")
print ("angularjs-csti-scanner")
os.system("git clone https://github.com/tijme/angularjs-csti-scanner.git")
os.system("clear")
print ("wssip")
os.system("git clone https://github.com/nccgroup/wssip.git")
os.system("clear")
print ("owtf")
os.system("git clone https://github.com/owtf/owtf.git")
os.system("clear")
print ("fuzzapi")
os.system("git clone https://github.com/lalithr95/fuzzapi.git")
os.system("clear")
print ("timing_attack")
os.system("git clone https://github.com/ffleming/timing_attack.git")
os.system("clear")
print ("commix")
os.system("git clone https://github.com/commixproject/commix.git")
os.system("clear")
print ("jexboss")
os.system("git clone https://github.com/joaomatosf/jexboss.git")
os.system("clear")
print ("wordpress-exploit-framework")
os.system("git clone https://github.com/rastating/wordpress-exploit-framework.git")
os.system("clear")
print ("vuls")
os.system("git clone https://github.com/future-architect/vuls.git")
os.system("clear")
print ("grabber")
os.system("git clone https://github.com/neuroo/grabber.git")
os.system("clear")
print ("wikto")
os.system("git clone https://github.com/sensepost/wikto.git")
os.system("clear")
print ("basic-auth-pot")
os.system("git clone https://github.com/bjeborn/basic-auth-pot.git")
os.system("clear")
print ("nikto")
os.system("git clone https://github.com/sullo/nikto.git")
os.system("clear")
print ("Scout2")
os.system("git clone https://github.com/iSECPartners/Scout2.git")
os.system("clear")
print ("social-engineer-toolkit")
os.system("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
os.system("clear")
print ("beef")
os.system("git clone https://github.com/beefproject/beef.git")
os.system("clear")
print ("wpsploit")
os.system("git clone https://github.com/espreto/wpsploit.git")
os.system("clear")
print ("wpscan")
os.system("git clone https://github.com/wpscanteam/wpscan.git")
os.system("clear")
print ("p0wny-shell")
os.system("git clone https://github.com/flozz/p0wny-shell.git")
os.system("clear")
print ("AutoHackingUsb")
os.system("git clone https://github.com/xyse/AutoHackingUsb")
os.system("clear")
os.system("git clone https://github.com/m4ll0k/Infoga.git")
os.system("clear")
os.system("git clone https://github.com/EmpireProject/Empire.git")
os.system("clear")
os.system("git clone https://github.com/getsecnow/Sn1per.git")
os.system("clear")
os.system("git clone https://github.com/Gameye98/Black-Hydra.git")


